# Generated by Django 4.1.3 on 2022-12-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_publicacion_imagen_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='celular',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
