# Generated by Django 4.1.3 on 2022-12-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicacion_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_libro',
            field=models.ImageField(blank=True, default='static/img/img_default.png', upload_to='../media/static/img'),
        ),
    ]
