# Generated by Django 4.1.3 on 2022-12-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_publicacion_imagen_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_libro',
            field=models.ImageField(blank=True, default='\\media\\img_default.png', upload_to='media/'),
        ),
    ]
